### ISSUE TITLE
Support for newer Versions / SearchGuard

### ISSUE THREAD

**Issue by dbt4u** [TrumanDu/cleaner#1]
Hello together,

we love this very easy curator plugin for Kibana. Did you have support for newer Kibana Versions, like 6.6 or even 7.x? 

Did cleaner work with auth / encrypted environments like SearchGuard and/or XPack-Security? Esp. with SearchGuard we have the Problem that "cleaner" did not work. Every request is blocked "unauthorized".

BR

**Comment by dbt4u** [comment]
Find an ELK-Stack with buildin SearchGuard, here: https://github.com/deviantony/docker-elk

**Comment by dbt4u** [comment]
here the cross-posting in the ELK-Stack github: https://github.com/deviantony/docker-elk/issues/364

**Comment by dbt4u** [comment]
Here are the Get-Request which creates the "403" Response: 
https://[kibana-url]/api/cleaner/list

**Comment by TrumanDu** [comment]
@CodeFreezr thanks for you attention! yeah,we can upgrate this plugin.but will cost some day.Can I know which company you are?I hope you can make more suggestions.if you like it,please give me star,thanks!

**Comment by dbt4u** [comment]
We have found a complete new feature in Elastic Search 6.6+ ILM = Index Lifecycle Management, which includes also a "delete index" stage. Not sure if it makes sense to maintain furter versions.
