### ISSUE TITLE
Version 7.x / OSS / ODFE Support

### ISSUE THREAD

**Issue by dbt4u** [TrumanDu/cleaner#3]
Because the build-in ILM Solutions are to complex we looking for smarter solution. We found cleaner really smart and handy, but do you support the new 7.x OSS/Versions of ELS and Kibana? We would like to use cleaner inside the OpenDistro for Elasticsearch v1.2++

https://opendistro.github.io/for-elasticsearch/

**Comment by TrumanDu** [comment]
@CodeFreezr yeah,will cost some day!

**Comment by dbt4u** [comment]
Funstastic! So I will spread the words in our team. Conversely we could create some promotions, talk with some aws-guys about, boost some social media stuff, ...

**Comment by dbt4u** [comment]
Any Ideas about a possible schedule?

**Comment by TrumanDu** [comment]
a week later

**Comment by TrumanDu** [comment]
it's work! [7.4.2](https://github.com/TrumanDu/cleaner/releases/tag/7.4.2)
